name: liquid_glass_navbar
description: "A high-performance Flutter plugin bringing the native iOS Liquid Glass navigation bar to Flutter apps with custom SVGs, PNGs, and IconData."
version: 1.1.0
homepage: "https://github.com/bakarflutter/glass_nav_bar"
repository: "https://github.com/bakarflutter/glass_nav_bar"
issue_tracker: "https://github.com/bakarflutter/glass_nav_bar/issues"

environment:
    sdk: ^3.9.2
    flutter: ">=3.3.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_svg: ^2.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    plugin:
        platforms:
            ios:
                pluginClass: NativeLiquidTabBarPlugin
